apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |-
    global:
    scrape_configs:
    - job_name: 'testspring'
      metrics_path: '/actuator/prometheus'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_container_port_number]
        separator: ';'
        regex: '(.*);(.*)'
        replacement: '${1}:8080'
        target_label: '__address__'
      - source_labels: [__meta_kubernetes_pod_label_run]
        regex: 'testspring'
        action: keep
    - job_name: 'test8090'
      metrics_path: '/actuator/prometheus'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_container_port_number]
        separator: ';'
        regex: '(.*);(.*)'
        replacement: '${1}:8090'
        target_label: '__address__'
      - source_labels: [__meta_kubernetes_pod_label_run]
        regex: 'test8090'
        action: keep
